# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Trishala
paginate:       5
baseurl:        ""
url:            "https://trishalaneeraj.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Trishala Neeraj
  url:          http://chester.how
  email:        tn338@cornell.edu

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

remote_theme: chesterhow/tale

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
