# Site settings
title:
email: tn338 @ cornell.edu
url: https://trishalaneeraj.github.io
description: "'Because the people who are crazy enough to think they can change the world, are the ones who do.' - Apple Think Different"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Trishala Neeraj

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/trishala-neeraj
  - title: github
    url: https://github.com/trishalaneeraj
  - title: instagram
    url: https://www.instagram.com/trishalaneeraj/



# Build settings
markdown: kramdown
permalink: pretty
